// Generated by CoffeeScript 1.8.0
(function() {
  var App, MojioClient, buildMojioMap, config, mojio_client;

  MojioClient = this.MojioClient;

  config = {
    application: '8e1a4042-9eb7-4d2a-a6a1-6c0d8168b4e2', //Replace with your application id
    secret: 'b5e18603-eb22-46a3-9f77-8dd6cabc9c37', // Replace with your secret id
    hostname: 'api.moj.io',
    version: 'v1',
    port: '443',
    scheme: 'https',
    login: 'taskr130', // Replace with your login
    password: 'tUmbuhan1' //Replace with your password
  };

  mojio_client = new MojioClient(config);

  App = mojio_client.model('App');

  $(function() {
    var div;
    if (config.application === '[YOUR APP ID GOES HERE]') {
      div = document.getElementById('result');
      div.innerHTML += 'Mojio Error:: Set your application and secret keys in myFirstMojioApp source code.  <br>';
      return;
    }
    mojio_client.login(config.login, config.password, function(error, result) {
      if (error) {
        return alert("Login Error:" + error);
      } else {
        alert("Authorization Successful.");
        div = $("#welcome");
        div.html('Authorization Result:<br />');
        div.append(JSON.stringify(result));
        mojio_client.get(mojio_client.model("User"), {
          id: result.UserId
        }, function(error, result) {
          var message;
          message = '<br/><br/>Viewing the location of <strong>';
          if (result.FirstName) {
            message += result.FirstName;
          } else if (result.UserName) {
            message += result.UserName;
          } else if (result.LastName) {
            message += result.LastName;
          } else if (result.Email) {
            message += result.Email;
          } else {
            message += "Unknown";
          }
          message += '</strong>';
          div = $("#welcome");
          return div.append(message);
        });
        // return mojio_client.get(mojio_client.model("Vehicle"), {}, function(error, result) {
        //   var i, lat, lng;
        //   lat = [];
        //   lng = [];
        //   i = 0;
        //   $.each(result.Data, function(key, value) {
        //     if ((value.LastLocation != null) && (value.LastLocation.Lat != null) && (value.LastLocation.Lng != null)) {
        //       lat[i] = value.LastLocation.Lat;
        //       lng[i] = value.LastLocation.Lng;
        //       return i++;
        //     }
        //   });
        //   div = $("#result");
        //   if (lat.length > 0) {
        //     div.html('The vehicle is in: ' + lat[0] + ", " + lng[0]);
        //     return buildMojioMap(lat[0], lng[0]);
        //   } else {
        //     return div.html("No vehicle detected!");
        //   }
        // });
        
        //////////////////////////////////////////////////////////////////////////////////////
        //work
        //////////////////////////////////////////////////////////////////////////////////////

        // return mojio_client.get(mojio_client.model("Vehicle"), {}, function(error, result) {
        //   var maxSpeed, i, VIN, fuelLevel;
        //   i = 0;

        //   // $.each(result.Data, function(key,value){
        //   //   if (value.lastSpeed > 0){
        //   //     maxSpeed = value.lastSpeed;
        //   //     return i++;
        //   //   }
        //   // });

        //   $.each(result.Data, function(key, value){
        //     if (value.VIN != null)
        //     {
        //       VIN = value.VIN;
        //       fuelLevel = value.FuelLevel;
        //     }
        //     // if (value.fuelLevel != null)
        //     // {
        //     //   fuelLevel = value.fuelLevel;
        //     // }
        //   });


        //   div = $("#result");
        //    rs = $("#sresult");
        //   if (VIN!=null)
        //   {
        //     //div.html('Vin number: ' + VIN); 
        //     //div.append(JSON.stringify(result)); 
        //      rs.html('fuelLevel: ' + fuelLevel)
        //   }
        //   else
        //   {
        //     div.html('there is no VIN number');
        //   }
          
        // });

      ////////////////////////////////////////////////////////////////////



        // return mojio_client.get(mojio_client.model("Trip"), {}, function(error, result) {
        //   div = $("#sresult");
        //   div.append(JSON.stringify(result));
        // });

        return mojio_client.get(mojio_client.model("Trip"),{},function(error, result){
          var str = "";

          div = $("#result");
          if (error)
            div.html("Get trips error");
          else
          {
            var trips = [], i = 0;
            //div.html("proceed");

            $.each(result.Data, function(key, value){
              trips[i] = new Trip(result.Data[i]);
              div.html("hello" + i);
              return i++;
            
          });

            // if (result instanceof Array){
            //   var arrlength = result.length;
            //   for (; i<arrlength ; i++){
            //     trips[i] = new Trip(result[i]);
            //   }
            // }
            
           // else if (result.Data instanceof Array) {
           //      var arrlength = result.Data.length;
           //      for (; i < arrlength; i++) {
           //          trips[i] = new Trip(result.Data[i]);
           //      }
           //    }
            // else if ((result.Data != null)){
            //   trips[i] = new Trip(result.Data);
            // }
            // else
            // {
            //   trips[i] = new Trip(result);
            // }

            div.empty();
            div.html("test");
            // if (i>0)
            // {
            //   for (var j = 0; j<i; j++)
            //   {
            //       div.html("trips found" + j );
            //   }
            // }
            // else
            // {
            //   div.html("No Trips found");
            // }
          }//end of else
        });

/////////////////////////////////////////////////////
        // return mojio_client.get(mojio_client("Vehicle"),{}, function(error, result){

        //   // var maxSpeed, fuelLevel;

        //   // var i = 0;

        //   // $.each(result.Data, function(key, value){
        //   //   if (value.maxSpeed != null ){
        //   //     maxSpeed = value.maxSpeed; 
        //   //     return i++;
        //   //   }
        //   // });



        //   div = $("#result");
        //   div.html('test');

        //   // if (error != null)
        //   //   return div.html("No vehicle max speed");
        //   // else
        //   // {
        //   //   div.html('The max speed is at: ' + maxSpeed);
        //   //   return maxSpeed;
        //   // }


        // });


///////////////////////////////////////////////////

//         return mojio_client.get('trips',null,null,15).done( function( results ) {
//     // Iterate over each trip
//     for( i = 0; i < results.Data.length ; i++ )
//     {
//         // Trip
//         var trip = results.Data[i];
//         // Do something with each trip
//         // ...
//         return div.html(trip);
//     }
// });

///////////////////////////////////////////////
      }
    });
    return $("#button").click(function() {
      return mojio_client.unauthorize(config.redirect_uri);
    });
  });

  // showTrips = function(){
  //   mojio_client.get(mojio_client.model("Trip"), {}, function(error, result) {
  //         div = $("#sresult");
  //         div.append(JSON.stringify(result));
  //       });
  // };

  buildMojioMap = function(mojioLat, mojioLng) {
    var map;
    map = new GMaps({
      el: '#map',
      lat: mojioLat,
      lng: mojioLng,
      panControl: false,
      streetViewControl: false,
      mapTypeControl: false,
      overviewMapControl: false
    });
    return setTimeout(function() {
      return map.addMarker({
        lat: mojioLat,
        lng: mojioLng,
        animation: google.maps.Animation.DROP,
        draggable: false,
        title: 'Current Mojio Location'
      }, 1000);
    });
  };

}).call(this);


// return mojio_client.query(mojio_client.model("Trip"), {}, function(error, result){
        //   if error?
        //     console.log("Error:"+error)
        //   else

//# sourceMappingURL=myFirstMojioAppOld.js.map
